// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Prisma CLI (migrate/db push/studio/seed) must use the direct Supabase
    // connection — the transaction pooler cannot run migrations.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
